name: Deploy Node App to EC2

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.Aikansh@008 }}" | docker login -u "${{ secrets.aikanshtiwari }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.aikanshtiwari }}/shakti-backend .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.aikanshtiwari }}/shakti-backend

    - name: SSH and Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.ssh -i "ShktiNxt2.pem" ec2-user@ec2-3-109-55-17.ap-south-1.compute.amazonaws.com }}
        script: |
          docker pull ${{ secrets.aikanshtiwari }}/shakti-backend
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 80:5000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/shakti-backend
